[project]
author = [
    {name = "Ivan Foksha", email = "v.foksh6@gmail.com"}
]
name = "hexlet-code"
version = "0.1.0"
description = "A tool to computer differences between files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
