name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install uv
          make install

      - name: Run linter and pytest
        run: |
          make check

      - name: Run test coverage
        run: |
          make test-coverage

      - name: Initialize SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@master
        with:
          login: ${{ secrets.SONAR_TOKEN }}
          organization: "ivanfoksha"
          projectKey: "IvanFoksha_python-project-50"
