name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install uv
          make install

      - name: Run linter and pytest
        run: |
          make check

      - name: Run test coverage
        run: |
          make test-coverage

      - name: Prepare SonarQube scan
        run: |
          echo "sonar.projectKey=IvanFoksha_python-project-50" > sonar-project.properties
          echo "sonar.sources=gendiff" >> sonar-project.properties
          echo "sonar.tests=tests" >> sonar-project.properties
          echo "sonar.testExecutionReportPaths=$PWD/coverage.xml" >> sonar-project.properties
          echo "sonar.python.version=3.12" >> sonar-project.properties

      - name: Initialize SonarCloud Scanner
        uses: SonarSource/sonarqude-scan-action@v5.0.0
        with:
          token: ${{ secret.SONAR_TOKEN }}
